### ISSUE TITLE
MCP2517FD

### ISSUE THREAD

**Issue by iDoka** [zjlywjh001/CAN_OMEGA#1]
Hello Jarvis!
You mentioned MCP2517FD controller which CAN FD support.
I seems device with this p/n has disappeared.
Google lists only a few results for "MCP2517FD", so a CAN-FD standalone controller was announced for end of 2015

Could you share any information of MCP2517FD e.g. datasheet?
Or even to advice alternatives of standalone CAN FD controller? (w/o CPU core)

Thanks,
Dmitry

**Comment by zjlywjh001** [comment]
MCP2517FD is still under development. It will be released soon as far as I know. I'm using MCP2515 for testing in current board.

**Comment by iDoka** [comment]
Much thanks for sharing info.
I'm waiting tapeout impatiently!

**Comment by iDoka** [comment]
Available now! http://www.microchip.com/wwwproducts/en/MCP2517FD
